Changed line 21 in lib/CambionCycle.js to this.state from this.active
WFCD/warframe-worldstate-parser pull request #427
Opened 2022-12-24 11:14 UTC by Neppkun

### What did you fix? 
Changed line 21 in lib/CambionCycle.js to `this.state` from `this.active`

---

### Evidence/screenshot/link to line

See [line 21](https://github.com/WFCD/warframe-worldstate-parser/compare/master...Neppkun:warframe-worldstate-parser:master?expand=1#diff-a55ae305eee93976388a02c2a0bfa88797fc42e68bb96ceec43c4a74f6b48440R21)

Here's a screenshot of my terminal using it as well: 
![image](https://user-images.githubusercontent.com/57060018/209433295-0b43b5b6-002c-4d14-9a10-f28200b01c54.png)

### Considerations
- Does this contain a new dependency? **No**
- Does this introduce opinionated data formatting or manual data entry? **Yes**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **Yes(?)**
- Have I run the linter? **No**
- Is is a bug fix, feature request, or enhancement? **Feature Request**

2022-12-24 15:38 UTC, TobiTenno requested changes
Not sure what you did but it looks like you rewrote the whole file. Check if you changed line endings or similar.

2022-12-24 16:30 UTC, Neppkun commented
> Not sure what you did but it looks like you rewrote the whole file. Check if you changed line endings or similar.
> 
> Additionally, for passivity, the state should be new and the same value as active, not just a name change.

Added back the old key. And I have no idea why Github says the entire file is overwritten, but it doesn't seem to be a problem ![image](https://cdn.discordapp.com/emojis/972809144472076298.webp?size=24&quality=lossless)

2022-12-27 02:03 UTC, TobiTenno commented
if you're on windows and you used notepad, it changed all of the line endings, so please start over and either do it from CLI, or do it from notepad++/vscode/atom/etc. and leave the line endings as LF

2022-12-27 14:21 UTC, Neppkun commented
> if you're on windows and you used notepad, it changed all of the line endings, so please start over and either do it from CLI, or do it from notepad++/vscode/atom/etc. and leave the line endings as LF

@TobiTenno oh, just noticed I was using CRLF. My bad, sorry. Changed it back to LF and it seems to be good now.

2022-12-27 17:36 UTC, TobiTenno commented
still showing all lines as CRLF

2022-12-27 18:55 UTC, Neppkun commented
> still showing all lines as CRLF

@TobiTenno Are you sure you're checking for repo lines and not working directory?

return of `git ls-files --eol` (where `i/[type]` is repository) shows LF
![image](https://user-images.githubusercontent.com/57060018/209710054-6cfb19d2-2ad8-4d71-a7a3-1cc2a6f16381.png)

opening the repo in github.dev also shows LF
![image](https://user-images.githubusercontent.com/57060018/209710147-5d6c29be-a81b-438d-ac57-26a83e558270.png)

2022-12-27 19:25 UTC, TobiTenno commented
i'm looking at the lint job and the diff on github. @Neppkun

2022-12-27 19:26 UTC, TobiTenno commented on lib/CambionCycle.js
>      this.active = cetusCycle.isDay ? 'fass' : 'vome';
```suggestion
    this.state = cetusCycle.isDay ? 'fass' : 'vome';
    this.active = this.state;
```

2022-12-27 20:35 UTC, Neppkun commented
Great then :D

2022-12-27 20:42 UTC, TobiTenno commented
oh, just noticed you didn't add unit tests... sorry, need to just add one to verify that new field

2022-12-27 22:57 UTC, Neppkun commented
I'm afraid I've got no clue how unit testing works. And besides, do you really need unit testing on one line of code that's just the previous line with a different name?

2022-12-28 00:11 UTC, TobiTenno commented
> I'm afraid I've got no clue how unit testing works. And besides, do you really need unit testing on one line of code that's just the previous line with a different name?

yeah, that's kinda the point of unit testing... to catch if something happens to that field. new name, etc.

just search for cambion tests... https://github.com/WFCD/warframe-worldstate-parser/blob/master/test/unit/cambion.spec.js#L65 add a copy of this line, then you're done

2022-12-28 13:47 UTC, Neppkun commented
> yeah, that's kinda the point of unit testing... to catch if something happens to that field. new name, etc.

Alright then, my bad. I just never  worked with unit tests so didn't know.

> just search for cambion tests... https://github.com/WFCD/warframe-worldstate-parser/blob/master/test/unit/cambion.spec.js#L65 add a copy of this line, then you're done

I believe I [did it](https://github.com/WFCD/warframe-worldstate-parser/pull/427/commits/9454ffb678a5ee9f747048c9b5bb30dd09c7cc94)

2022-12-28 15:43 UTC, TobiTenno commented
The unit test is fine, but I requested a logic change to reduce dupe code and you resolved it without response.

2022-12-28 15:43 UTC, TobiTenno commented on lib/CambionCycle.js
>      this.active = cetusCycle.isDay ? 'fass' : 'vome';
Please don't resolve if you both don't change and don't reply.

2022-12-28 17:52 UTC, Neppkun commented
> The unit test is fine, but I requested a logic change to reduce dupe code and you resolved it without response.

oh, I thought resolving applied the requested changes. My bad.

2022-12-29 00:29 UTC, TobiTenno approved these changes

2022-12-29 00:32 UTC, merged